pkgname=touchpadtoggle
pkgver=1
pkgrel=1
pkgdesc="toggles touchpad using synclient"
arch=('any')
license=('None')
depends=('xf86-input-synaptics' 'zsh')
source=('touchpadtoggle')
md5sums=('') # generated by Makefile

package() {
  install -d $pkgdir/usr/bin
  install -D -t $pkgdir/usr/bin touchpadtoggle
}

# vim:set ts=2 sw=2 et:
